language: node_js

node_js:
  - "10"

sudo: false

git:
  depth: 3

cache:
  directories:
    - node_modules

before_install:
  - npm install markdownlint-cli

install:
  - npm install

script:
  - markdownlint $PWD --ignore node_modules && npm test
  
