language: node_js

dist: bionic

node_js:
  - "10"

jdk: openjdk8

env:
 - DOCKER_COMPOSE_VERSION=1.24.1

sudo: false

git:
  depth: 3

services:
  - docker

# Npm caching is enabled by default since July 2019 - but explicitly set it so there's no confusion!
cache:
  npm: true

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - npm ci
  - npm run build

script:
  - markdownlint $PWD --ignore node_modules && npm test
  
