name: 1.0.0.$(Build.BuildID)

resources:
  - repo: self

pool:
  vmImage: ubuntu-16.04

pr: none
trigger:
  - master

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x' # replace this value with the version that you need for your project

  - script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
    echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)/bin:$(PATH)"
  - script: npm ci
  - script: npm run build
  - script: npx markdownlint $PWD --ignore node_modules
  - script: npm test
  - script: find ./node_modules -print -exec touch {} \;
  - script: ls -ltd $(find .)

  - task: NuGetCommand@2
    displayName: 'NuGet pack'
    inputs:
      command: pack
      packagesToPack: '$(Build.SourcesDirectory)/managedserver.nuspec'
      versioningScheme: byBuildNumber

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      publishVstsFeed: '$(NugetFeed)'
